import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Archive, ArrowLeft, Check, ChevronRight, Download, ExternalLink, FilePlus2, FolderSearch, LayoutList, Pencil, Plus, RefreshCw, Search, Settings2, Tag, Trash2, Upload, X } from 'lucide-react';
import avatarUrl from './assets/miaoxi-avatar.png';
import './styles.css';
import './picker.css';
import './layout.css';
import './theme.css';

const baseApi = window.invoiceApi;
const api = {
  ...baseApi,
  openInvoice: async (filePath) => {
    try {
      const error = await baseApi.openInvoice(filePath);
      if (error) alert(`无法打开 PDF：${error}`);
      return error;
    } catch (error) {
      alert(`无法打开 PDF：${error.message}`);
      return error.message;
    }
  }
};
const fmt = (v) => `¥${Number(v || 0).toFixed(2)}`;
const today = () => new Date().toISOString().slice(0, 10);

function Modal({ title, children, onClose }) { return <div className="overlay"><section className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={onClose}><X size={18}/></button></div>{children}</section></div>; }
function Empty({ icon: Icon, title, text, action }) { return <div className="empty"><Icon size={34}/><h3>{title}</h3><p>{text}</p>{action}</div>; }
function Badge({ children, type = 'neutral' }) { return <span className={`badge ${type}`}>{children}</span>; }

function App() {
  const [data, setData] = useState(null); const [tab, setTab] = useState('invoices'); const [selected, setSelected] = useState(null);
  const [modal, setModal] = useState(null); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [notice, setNotice] = useState(''); const [activeProject, setActiveProject] = useState(null);
  const reload = async () => { const d = await api.bootstrap(); setData(d); return d; };
  useEffect(() => { reload(); }, []);
  const toast = (message) => { setNotice(message); setTimeout(() => setNotice(''), 3000); };
  const action = async (fn, message) => { try { const r = await fn(); if (r?.data) setData(r.data); else if (r?.invoices) setData(r); else await reload(); if(message) toast(message); return r; } catch (e) { toast(`操作失败：${e.message}`); } };
  if (!data) return <div className="loading">正在打开本地票据库…</div>;
  const invoices = data.invoices.filter(i => (!query || `${i.product_name} ${i.invoice_number} ${i.project_names.join(' ')} ${i.category_name}`.toLowerCase().includes(query.toLowerCase())) && (!statusFilter || i.status_name === statusFilter));
  return <main className={`app-shell theme-${data.theme || 'light'}`}>
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Archive size={20}/></div><span>票据管家</span></div>
      <nav><button className={tab==='invoices'?'active':''} onClick={()=>setTab('invoices')}><LayoutList size={18}/>我的发票 <b>{data.invoices.length}</b></button><button className={tab==='projects'?'active':''} onClick={()=>setTab('projects')}><FolderSearch size={18}/>项目管理</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings2 size={18}/>基础设置</button></nav>
      <div className="side-foot"><div className="creator-card"><div className="creator-avatar"><img src={avatarUrl} alt="MIAOXI 渺希"/></div><div className="creator-copy"><small className="creator-kicker">CREATOR NOTE</small><strong>made by MIAOXI</strong><span>渺希 · 票据管家</span><small>QQ 2703036328</small></div></div><div className="local-storage"><span>本地离线存储</span><small>{data.directory}</small></div></div>
    </aside>
    <section className={`content ${activeProject ? 'project-content' : ''}`}>
      {tab==='invoices' && <Invoices data={data} invoices={invoices} query={query} setQuery={setQuery} statusFilter={statusFilter} setStatusFilter={setStatusFilter} select={setSelected} action={action} setModal={setModal} />}
      {tab==='projects' && !activeProject && <Projects data={data} action={action} setModal={setModal} select={setSelected} openProject={setActiveProject} />}
      {tab==='projects' && activeProject && <ProjectDetail project={data.projects.find(p=>p.id===activeProject.id) || activeProject} data={data} action={action} back={()=>setActiveProject(null)} select={setSelected} setModal={setModal} toast={toast} />}
      {tab==='settings' && <Settings data={data} action={action} setModal={setModal} />}
    </section>
    {selected && <InvoiceDrawer invoice={selected} data={data} onClose={()=>setSelected(null)} action={action} setModal={setModal} />}
    {modal && <Modal title={modal.title} onClose={()=>setModal(null)}>{modal.content}</Modal>}
    {notice && <div className="notice"><Check size={16}/>{notice}</div>}
  </main>;
}

function Invoices({ data, invoices, query, setQuery, statusFilter, setStatusFilter, select, action, setModal }) {
  const toastResult = (results, label='处理完成') => { const added=results.filter(x=>x.id).length, skipped=results.filter(x=>x.skipped).length, duplicates=results.filter(x=>x.duplicate).length, failed=results.filter(x=>x.parsed?.parse_state==='待人工补充').length; const details=results.filter(x=>x.duplicate||x.parsed?.parse_state==='待人工补充').slice(0,8).map(x=>`${x.file?.split('\\').pop()}: ${x.duplicate?'发票号码重复':'解析失败，待人工补充'}`).join('\n'); alert(`${label}：新增 ${added} 份，重复 ${duplicates} 份，已跳过 ${skipped} 份，待人工补充 ${failed} 份。${details?`\n\n${details}`:''}`); };
  const upload = async () => { const files=await api.chooseFiles(); if(files.length) { const r=await action(()=>api.importFiles(files),`已处理 ${files.length} 份发票`); if(r?.results) toastResult(r.results,'导入完成'); } };
  const scan = async () => { const r=await action(()=>api.scanDirectory()); if(r?.results) toastResult(r.results,'扫描完成'); };
  return <><header className="page-head"><div><p className="eyebrow">INVOICE LIBRARY</p><h1>我的发票</h1><p className="muted">统一核对、归类和管理本机票据</p></div><div className="head-actions"><button className="secondary" onClick={async()=>{const result=await api.exportAllInvoices();if(result) alert(`已导出：${result}`)}}><Download size={17}/>导出全部 Excel</button><button className="secondary" onClick={scan}><FolderSearch size={17}/>扫描文件夹</button><button className="primary" onClick={upload}><Upload size={17}/>导入 PDF</button></div></header>
    <div className="summary"><Metric label="发票总数" value={data.invoices.length}/><Metric label="待报销金额" value={fmt(data.invoices.filter(i=>i.status_name==='未报销').reduce((a,i)=>a+Number(i.total_amount),0))}/><Metric label="报销中" value={data.invoices.filter(i=>i.status_name==='报销中').length}/><Metric label="待人工补充" value={data.invoices.filter(i=>i.parse_state==='待人工补充').length}/></div>
    <div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索商品、发票号码、项目"/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">全部状态</option>{data.statuses.map(s=><option key={s.id}>{s.name}</option>)}</select><span className="result-count">{invoices.length} 条记录</span></div>
    {invoices.length ? <div className="table-wrap"><table><thead><tr><th>序号</th><th>票据</th><th>类目 / 项目</th><th>金额</th><th>状态</th><th>解析</th><th></th></tr></thead><tbody>{invoices.map((i,index)=>{const missing=missingFields(i);const incomplete=i.parse_state==='待人工补充'||missing.length>0;return <tr key={i.id} onClick={()=>select(i)} onDoubleClick={()=>api.openInvoice(i.current_path)} title="双击打开 PDF"><td>{index+1}</td><td><strong>{i.product_name}</strong><small>{i.invoice_number || '暂无发票号码'} · {i.invoice_date || '日期待补充'}</small>{incomplete&&<small style={{color:'#b93b32',fontWeight:700,marginTop:5}}>请补充：{missing.length?missing.join('、'):'请核对解析内容'}</small>}</td><td><span>{i.category_name || '未分类'}</span><small>{i.project_names.length ? i.project_names.join('、') : '无项目'}</small></td><td className="amount">{fmt(i.total_amount)}<small>税额 {fmt(i.tax_amount)}</small></td><td><Badge type={statusType(i.status_name)}>{i.status_name}</Badge></td><td><Badge type={incomplete?'warn':'success'}>{incomplete?'待人工补充':'已解析'}</Badge></td><td><button className="open-pdf-button" onClick={e=>{e.stopPropagation();api.openInvoice(i.current_path)}}><ExternalLink size={14}/>打开</button><button className="table-edit" onClick={e=>{e.stopPropagation();select(i)}}><Pencil size={15}/>编辑</button>{incomplete&&<button className="retry-button" onClick={e=>{e.stopPropagation();action(()=>api.reparseInvoice(i.id),'已重新解析')}}>重试</button>}</td></tr>})}</tbody></table></div> : <Empty icon={FilePlus2} title="还没有发票" text="导入 PDF，或扫描已设置的发票文件夹。" action={<button className="primary" onClick={upload}><Upload size={17}/>导入 PDF</button>}/>}</>;
}
function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function statusType(s) { return s==='已报销'?'success':s==='不能报销'?'danger':s==='报销中'?'info':'warn'; }
function missingFields(invoice) { return [[!invoice.product_name || invoice.product_name==='待人工补充','商品名称'],[!Number(invoice.total_amount),'价税合计'],[!invoice.invoice_number,'发票号码'],[!invoice.invoice_date,'开票日期']].filter(([missing])=>missing).map(([,label])=>label); }

function InvoiceDrawer({ invoice, data, onClose, action, setModal }) {
  const [form,setForm]=useState({...invoice, tags: invoice.tags || []});
  const update = (k,v)=>setForm(f=>({...f,[k]:v}));
  const save=async()=>{const r=await action(()=>api.updateInvoice(invoice.id,form),'发票已更新'); if(r) onClose();};
  const addTag=()=>setModal({title:'新建标签',content:<NameForm label="标签名称" onSubmit={async n=>{await action(()=>api.addTag(n),'标签已创建'); setModal(null);}}/>});
  return <aside className="drawer"><div className="drawer-head"><div><p className="eyebrow">发票详情</p><h2>{invoice.product_name}</h2></div><button className="icon" onClick={onClose}><X size={19}/></button></div><div className="drawer-actions"><button className="secondary" onClick={()=>api.openInvoice(invoice.current_path)}>打开 PDF</button><button className="danger-btn" onClick={()=>{ if(confirm('仅移除系统记录，保留 PDF 文件？')) action(()=>api.deleteInvoice(invoice.id,false),'已移除记录').then(onClose); }}><Trash2 size={15}/></button></div>
    <div className="form-grid"><Field label="商品名称"><input value={form.product_name} onChange={e=>update('product_name',e.target.value)}/></Field><Field label="价税合计"><input type="number" step="0.01" value={form.total_amount} onChange={e=>update('total_amount',e.target.value)}/></Field><Field label="类目"><select value={form.category_name||''} onChange={e=>update('category_name',e.target.value)}>{data.categories.map(c=><option key={c.id}>{c.name}</option>)}</select></Field><Field label="报销状态"><select value={form.status_name} onChange={e=>update('status_name',e.target.value)}>{data.statuses.map(s=><option key={s.id}>{s.name}</option>)}</select></Field><Field label="发票号码"><input value={form.invoice_number} onChange={e=>update('invoice_number',e.target.value)}/></Field><Field label="开票日期"><input type="date" value={String(form.invoice_date||'').replace(/[年/月日 ]/g,'-').slice(0,10)} onChange={e=>update('invoice_date',e.target.value)}/></Field></div>
    <Field label="标签"><div className="tag-pick">{data.tags.map(t=><label key={t.id}><input type="checkbox" checked={form.tags.includes(t.name)} onChange={e=>update('tags',e.target.checked?[...form.tags,t.name]:form.tags.filter(x=>x!==t.name))}/>{t.name}</label>)}<button className="text-button" onClick={addTag}><Plus size={14}/>标签</button></div></Field><Field label="备注"><textarea rows="3" value={form.notes||''} onChange={e=>update('notes',e.target.value)}/></Field>
    <section className="relations"><div className="section-title"><h3>关联项目</h3><button className="text-button" onClick={()=>setModal({title:'关联至项目',content:<ProjectLink data={data} invoice={invoice} action={action} close={()=>setModal(null)}/>})}><Plus size={15}/>关联</button></div>{invoice.project_names.length?<p>{invoice.project_names.join('、')}</p>:<p className="muted">尚未关联项目，文件使用“待报销”命名。</p>}</section><button className="primary wide" onClick={save}><Check size={17}/>保存并同步文件名</button></aside>;
}
function Field({label,children}) { return <label className="field"><span>{label}</span>{children}</label>; }
function NameForm({ label, onSubmit, extra }) { const [name,setName]=useState(''); return <form className="stack" onSubmit={e=>{e.preventDefault();if(name.trim())onSubmit(name.trim());}}><Field label={label}><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={`输入${label}`}/></Field>{extra}<button className="primary" type="submit">确认创建</button></form>; }
function ProjectLink({ data, invoice, action, close }) { const [project,setProject]=useState(''); const [primary,setPrimary]=useState(true); return <form className="stack" onSubmit={async e=>{e.preventDefault();if(project){await action(()=>api.linkInvoice(Number(project),invoice.id,primary),'项目关联已更新');close();}}}><Field label="选择项目"><select value={project} onChange={e=>setProject(e.target.value)}><option value="">请选择</option>{data.projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><label className="check"><input type="checkbox" checked={primary} onChange={e=>setPrimary(e.target.checked)}/>设为主项目（决定文件名和编号）</label><button className="primary">确认关联</button></form>; }

function Projects({ data, action, setModal, select, openProject }) {
  const create=()=>setModal({title:'新建报销项目',content:<ProjectCreate action={action} close={()=>setModal(null)}/>});
  const edit=(project)=>setModal({title:'编辑项目',content:<ProjectEdit project={project} action={action} close={()=>setModal(null)}/>});
  const archive=(project)=>action(()=>api.archiveProject(project.id,!project.archived),project.archived?'项目已恢复为活动状态':'项目已归档，文件前缀已更新');
  const remove=async(project)=>{if(confirm(`删除项目“${project.name}”？\n项目文件夹会移入回收站；“所有发票”中的主票据会保留。`)) await action(()=>api.deleteProject(project.id),'项目已删除，主票据已保留');};
  return <><header className="page-head"><div><p className="eyebrow">REIMBURSEMENT PROJECTS</p><h1>项目管理</h1><p className="muted">按项目组织票据，完成后导出核对清单</p></div><button className="primary" onClick={create}><Plus size={17}/>新建项目</button></header><div className="project-grid">{data.projects.map(p=><article className={`project-card ${p.archived?'archived':''}`} key={p.id}><div className="project-card-top"><div className="folder-icon"><FolderSearch size={19}/></div><div><button className="icon" title="编辑项目" onClick={()=>edit(p)}><Pencil size={17}/></button><button className="icon" title={p.archived?'恢复项目':'归档项目'} onClick={()=>archive(p)}><Archive size={17}/></button><button className="icon" title="删除项目" onClick={()=>remove(p)}><Trash2 size={17}/></button><button className="icon" title="导出 Excel" onClick={async()=>{const r=await api.exportProject(p.id); if(r) alert(`已导出：${r}`);}}><Download size={17}/></button></div></div><h2>{p.name} {p.archived?<Badge type="neutral">已归档</Badge>:null}</h2><p>{p.note||'暂无项目说明'}</p><div className="project-stats"><span>{p.invoice_count} 张发票</span><strong>{fmt(p.total)}</strong></div>{p.archived?<button className="restore-project" onClick={()=>archive(p)}><Archive size={16}/>恢复为活动项目</button>:<button className="card-link" onClick={()=>openProject(p)}>进入项目 <ChevronRight size={16}/></button>}</article>)}{!data.projects.length&&<Empty icon={FolderSearch} title="创建你的第一个项目" text="将发票按学校报销项目归集，随时导出 Excel。" action={<button className="primary" onClick={create}><Plus size={17}/>新建项目</button>}/>}</div></>;
}
function ProjectCreate({action,close}) { const [note,setNote]=useState(''); return <NameForm label="项目名称" extra={<Field label="项目说明"><textarea value={note} onChange={e=>setNote(e.target.value)} rows="3"/></Field>} onSubmit={async n=>{await action(()=>api.createProject(n,note),'项目已创建');close();}}/>; }
function ProjectEdit({project,action,close}) { const [name,setName]=useState(project.name); const [note,setNote]=useState(project.note||''); return <form className="stack" onSubmit={async e=>{e.preventDefault();if(name.trim()){await action(()=>api.updateProject(project.id,{name,note}),'项目已更新');close();}}}><Field label="项目名称"><input autoFocus value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="项目说明"><textarea value={note} onChange={e=>setNote(e.target.value)} rows="3"/></Field><button className="primary" type="submit"><Check size={16}/>保存项目</button></form>; }
function ProjectDetail({ project, data, action, back, select, setModal, toast }) {
  const [showStats,setShowStats] = useState(true); const [projectStatus,setProjectStatus] = useState('');
  const rows = data.invoices.filter(i => i.project_names.includes(project.name)).sort((a,b)=>Number(a.project_sequences?.[project.id]||0)-Number(b.project_sequences?.[project.id]||0));
  const visibleRows = projectStatus ? rows.filter(row=>row.status_name===projectStatus) : rows;
  const upload = async () => { const files = await api.chooseFiles(); if (files.length) await action(() => api.importFiles(files, project.id), `已添加 ${files.length} 份发票到项目`); };
  const pickExisting = () => setModal({ title: `添加发票至 ${project.name}`, content: <InvoicePicker project={project} data={data} action={action} close={()=>setModal(null)} /> });
  const reconcile = async () => { const result = await action(() => api.reconcileFiles()); if (result) toast(result.failures.length ? `校验完成，${result.failures.length} 份文件需处理` : `一致性校验完成，已同步 ${result.checked} 份发票`); };
  const edit=()=>setModal({title:'编辑项目',content:<ProjectEdit project={project} action={action} close={()=>setModal(null)}/>});
  const archive=()=>action(()=>api.archiveProject(project.id,!project.archived),project.archived?'项目已恢复为活动状态':'项目已归档，文件前缀已更新');
  const remove=async()=>{if(confirm(`删除项目“${project.name}”？\n项目文件夹会移入回收站；“所有发票”中的主票据会保留。`)){await action(()=>api.deleteProject(project.id),'项目已删除，主票据已保留');back();}};
  const active=!project.archived;
  const tableBody = rows.length ? <div className="table-wrap"><table><thead><tr><th className="center-cell">序号</th><th>发票</th><th>类目</th><th className="center-cell">金额</th><th className="center-cell">状态</th><th></th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.id} onDoubleClick={()=>api.openInvoice(row.current_path)} title="双击打开 PDF"><td className="sequence-cell">{String(row.project_sequences?.[project.id]||'').padStart(3,'0')}</td><td><strong>{row.product_name}</strong><small>{row.invoice_number || '待补充'}</small></td><td>{row.category_name}</td><td className="amount centered-amount">{fmt(row.total_amount)}</td><td className="center-cell"><Badge type={statusType(row.status_name)}>{row.status_name}</Badge></td><td><button className="open-pdf-button" onClick={e=>{e.stopPropagation();api.openInvoice(row.current_path)}}><ExternalLink size={14}/>打开</button><button className="table-edit" onClick={()=>select(row)}><Pencil size={15}/>编辑</button>{active&&<button className="icon" title="移除项目发票" onClick={()=>action(()=>api.unlinkInvoice(project.id,row.id),'已移出项目')}><X size={16}/></button>}</td></tr>)}</tbody></table></div> : <Empty icon={FilePlus2} title="项目暂未添加发票" text={active?'上传 PDF，或从“我的发票”中选择已有发票。':'归档项目暂未保留发票。'} action={active?<button className="primary" onClick={pickExisting}><Plus size={16}/>添加发票</button>:null}/>;
  return <div className="project-workspace"><header className="page-head"><div><button className="back-button" onClick={back}><ArrowLeft size={16}/>项目管理</button><p className="eyebrow">PROJECT WORKSPACE</p><h1>{project.name} {project.archived?<Badge type="neutral">已归档</Badge>:null}</h1><p className="muted">{project.archived?'归档项目保留文件夹，票据前缀固定为“已报销项目”。':(project.note || '将发票添加到项目后，会自动复制到同名项目文件夹。')}</p></div><div className="head-actions"><button className="secondary" onClick={edit}><Pencil size={16}/>编辑项目</button><button className="secondary" onClick={archive}><Archive size={16}/>{project.archived?'恢复项目':'归档项目'}</button><button className="danger-btn" onClick={remove}><Trash2 size={16}/>删除项目</button><button className="secondary" onClick={reconcile}><RefreshCw size={16}/>一致性校验</button>{active&&<button className="secondary" onClick={pickExisting}><Plus size={16}/>从我的发票添加</button>}{active&&<button className="primary" onClick={upload}><Upload size={16}/>上传发票</button>}</div></header><section className="project-overview-toggle"><div><strong>项目数据看板</strong><span>{rows.length} 张发票 · {fmt(rows.reduce((sum,row)=>sum+Number(row.total_amount||0),0))}</span></div><button className="secondary" onClick={()=>setShowStats(!showStats)}>{showStats?'收起看板':'展开看板'}</button></section>{showStats&&<ProjectStats rows={rows}/>}<div className="project-detail-actions"><div className="project-filter"><span>发票状态</span><select value={projectStatus} onChange={e=>setProjectStatus(e.target.value)}><option value="">全部状态</option>{data.statuses.map(status=><option key={status.id} value={status.name}>{status.name}</option>)}</select><small>显示 {visibleRows.length} / {rows.length} 张</small></div><button className="secondary" onClick={async()=>{const result=await api.exportProject(project.id);if(result)toast(`已导出：${result}`)}}><Download size={16}/>导出 Excel 清单</button></div><section className="project-table-region">{tableBody}</section></div>;
}
function ProjectStats({ rows }) {
  const total = rows.reduce((sum, row) => sum + Number(row.total_amount || 0), 0);
  const statusMap = new Map(); rows.forEach(row => { const item=statusMap.get(row.status_name)||{count:0,amount:0}; item.count += 1; item.amount += Number(row.total_amount||0); statusMap.set(row.status_name,item); });
  const statusTotals = (name) => statusMap.get(name) || { count: 0, amount: 0 };
  const categoryMap = new Map(); rows.forEach(row => { const name=row.category_name||'未分类'; categoryMap.set(name,(categoryMap.get(name)||0)+Number(row.total_amount||0)); });
  const categories=[...categoryMap.entries()].sort((a,b)=>b[1]-a[1]); const maxCategory=categories[0]?.[1]||1;
  return <section className="stats-panel"><div className="stats-heading"><div><p className="eyebrow">PROJECT OVERVIEW</p><h2>项目统计</h2></div><span className="stats-total">{fmt(total)}</span></div><div className="stats-cards stats-cards-wide"><Metric label="项目录入发票金额" value={fmt(total)}/><Metric label="已报销金额" value={fmt(statusTotals('已报销').amount)}/><Metric label="报销中金额" value={fmt(statusTotals('报销中').amount)}/><Metric label="未报销金额" value={fmt(statusTotals('未报销').amount)}/><Metric label="不能报销金额" value={fmt(statusTotals('不能报销').amount)}/><Metric label="发票总数" value={`${rows.length} 张`}/></div><div className="stats-lower"><div><h3>报销状态</h3><div className="status-list">{['已报销','报销中','未报销','不能报销'].map(name=>{const item=statusTotals(name);return <div className="status-line" key={name}><span><i className={`status-dot ${statusType(name)}`}/>{name}</span><b>{item.count} 张</b><em>{fmt(item.amount)}</em></div>})}</div></div><div><h3>类目金额分布</h3><div className="category-list">{categories.map(([name,amount])=><div className="category-line" key={name}><div><span>{name}</span><b>{fmt(amount)}</b></div><div className="bar-track"><i style={{width:`${Math.max(3,amount/maxCategory*100)}%`}}/></div></div>)}{!categories.length&&<p className="muted">添加发票后显示统计</p>}</div></div></div></section>;
}
function InvoicePicker({ project, data, action, close }) {
  const [selected, setSelected] = useState([]); const available = data.invoices.filter(i=>!i.project_names.includes(project.name));
  return <form className="stack" onSubmit={async e=>{e.preventDefault();for(const id of selected) await action(()=>api.linkInvoice(project.id,id,false));close();}}><p className="muted">选择后会复制 PDF 到“{project.name}”文件夹。</p>{available.length ? <div className="picker-list">{available.map(i=><label className="picker-row" key={i.id}><input type="checkbox" checked={selected.includes(i.id)} onChange={e=>setSelected(e.target.checked?[...selected,i.id]:selected.filter(x=>x!==i.id))}/><span><strong>{i.product_name}</strong><small>{fmt(i.total_amount)} · {i.invoice_number || '待补充'}</small></span></label>)}</div> : <p className="muted">没有可添加的发票。</p>}<button className="primary" disabled={!selected.length}>添加选中发票</button></form>;
}
function ProjectInvoices({project,data,action,select,close}) { const rows=data.invoices.filter(i=>i.project_names.includes(project.name)); return <div className="stack"><p className="muted">{rows.length} 张发票，合计 {fmt(rows.reduce((a,i)=>a+Number(i.total_amount),0))}</p>{rows.map(i=><div className="mini-row" key={i.id}><div><strong>{i.product_name}</strong><small>{i.invoice_number}</small></div><b>{fmt(i.total_amount)}</b><button className="icon" onClick={()=>{close();select(i);}}><Pencil size={15}/></button><button className="icon" title="移除项目关联" onClick={()=>action(()=>api.unlinkInvoice(project.id,i.id),'已移除项目关联')}><X size={16}/></button></div>)}<button className="secondary" onClick={async()=>{const r=await api.exportProject(project.id);if(r) alert(`已导出：${r}`);}}><Download size={16}/>导出 Excel 清单</button></div>; }

function Settings({data,action,setModal}) { const [color,mode]=(data.theme||'green-light').split('-'); const setTheme=(nextColor,nextMode)=>action(()=>api.setTheme(`${nextColor}-${nextMode}`),'主题已更新'); return <><header className="page-head"><div><p className="eyebrow">LOCAL CONFIGURATION</p><h1>基础设置</h1><p className="muted">设置扫描目录和票据元数据选项</p></div></header><div className="settings-grid"><section><h2>界面主题</h2><p>选择颜色和明暗模式。渺希花语主题含专属人物与玫瑰装饰。</p><div className="theme-section-label">主题颜色</div><div className="theme-picker palette-picker">{[['green','绿色'],['blue','蓝色'],['orange','橙色'],['pink','粉色'],['miaoxi','渺希花语']].map(([value,label])=><button key={value} className={`theme-option ${value} ${color===value?'selected':''}`} onClick={()=>setTheme(value,mode)}><i/>{label}</button>)}</div><div className="theme-section-label">显示模式</div><div className="theme-picker mode-picker">{[['light','浅色模式'],['dark','深色模式']].map(([value,label])=><button key={value} className={mode===value?'selected':''} onClick={()=>setTheme(color,value)}>{label}</button>)}</div></section><section><h2>发票文件夹</h2><p>系统扫描此目录中的 PDF，并在解析成功后重命名原始文件。</p><code>{data.directory}</code><button className="secondary" onClick={()=>action(()=>api.chooseDirectory(),'发票目录已更新')}><FolderSearch size={16}/>选择文件夹</button></section><SettingsList title="报销状态" items={data.statuses.map(x=>x.name)} add={()=>setModal({title:'新建报销状态',content:<NameForm label="状态名称" onSubmit={async n=>{await action(()=>api.addStatus(n),'状态已创建');setModal(null);}}/>})}/><SettingsList title="自定义标签" items={data.tags.map(x=>x.name)} add={()=>setModal({title:'新建标签',content:<NameForm label="标签名称" onSubmit={async n=>{await action(()=>api.addTag(n),'标签已创建');setModal(null);}}/>})}/><SettingsList title="报销类目" items={data.categories.map(x=>x.name)} add={()=>setModal({title:'新建类目',content:<NameForm label="类目名称" onSubmit={async n=>{await action(()=>api.addCategory(n),'类目已创建');setModal(null);}}/>})}/></div></>; }
function SettingsList({title,items,add}) { return <section><div className="section-title"><h2>{title}</h2><button className="text-button" onClick={add}><Plus size={15}/>新建</button></div><div className="chips">{items.map(x=><span key={x}>{x}</span>)}{!items.length&&<p className="muted">暂无</p>}</div></section>; }

createRoot(document.getElementById('root')).render(<App/>);
